name: Linters

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: 🚀 Run yamllint
        uses: reviewdog/action-yamllint@b5f7217d8c815ae374d1d55840d5e569d82f01f0 # v1
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: 🚀 Run markdownlint
        uses: reviewdog/action-markdownlint@6f0e0e8703a9e840ffefa37a2775832c51c1c640 # v0
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}
