name: Linters

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: 🚀 Run yamllint
        uses: reviewdog/action-yamllint@5dd4640db975e4cac6f4e775a401695bafc28068 # v1
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: 🚀 Run markdownlint
        uses: reviewdog/action-markdownlint@34762a7b2dddebf3eb82f7e3a63b9d0242d0a42a # v0
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}
