name: Linters

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: 🚀 Run yamllint
        uses: reviewdog/action-yamllint@b5f7217d8c815ae374d1d55840d5e569d82f01f0 # v1
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: 🚀 Run markdownlint
        uses: reviewdog/action-markdownlint@844fd04b127b0d78328653f182d32988ad41d3d7 # v0
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}
