name: Zsh Benchmark

on:
  push:
    branches:
      - main
    paths:
      - .zfunctions/**
      - .zshrc.d/**
      - .zsh_plugins.txt
      - .zshenv
      - .zshrc
      - .zstyles
  pull_request:

permissions:
  pull-requests: write
  deployments: write
  contents: write

env:
  ZDOTDIR: ${{ github.workspace }}

jobs:
  benchmark:
    runs-on: macos-latest

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: 🏗️ Set Zsh environment (ZDOTDIR)
        run: |
          echo ". $ZDOTDIR/.zshenv" > ~/.zshenv

      - name: 🏗️ Init Zsh environment
        run: |
          echo "ZDOTDIR is set to: $ZDOTDIR"
        shell: zsh -li --rcs {0}
        env:
          TERM: screen-256color

      - name: 🚀 Run Zsh Benchmark
        run: zsh ./.github/scripts/zsh-benchmark.zsh
        shell: zsh -li --rcs {0}
        env:
          BENCHMARK_RESULT: benchmark-result.json
          TERM: screen-256color

      - name: 📥 Upload Benchmark Results
        uses: benchmark-action/github-action-benchmark@a60cea5bc7b49e15c1f58f411161f99e0df48372 # v1.22.0
        with:
          name: ${{ runner.os }}
          tool: customSmallerIsBetter
          output-file-path: benchmark-result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.event_name == 'push' }}
          comment-on-alert: ${{ github.event_name == 'pull_request' }}
          fail-on-alert: ${{ github.event_name == 'pull_request' }}
